"""empty message

Revision ID: 67c34fc8c91f
Revises: e5238b0acf31
Create Date: 2018-09-29 10:30:23.183857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c34fc8c91f'
down_revision = 'e5238b0acf31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('city_adcode', sa.String(length=6), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('type_code', sa.String(length=6), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('final_grid', sa.Integer(), nullable=True),
    sa.Column('adsl_server_url', sa.String(length=100), nullable=False),
    sa.Column('adsl_auth', sa.String(length=100), nullable=False),
    sa.Column('keys', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('city_adcode', 'type_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_missions')
    # ### end Alembic commands ###
