"""empty message

Revision ID: e5238b0acf31
Revises: a1b09924ef66
Create Date: 2018-09-29 10:28:45.879530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5238b0acf31'
down_revision = 'a1b09924ef66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenecode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('scenecode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenecode')
    # ### end Alembic commands ###
