"""empty message

Revision ID: fb6c8fdf401c
Revises: 67c34fc8c91f
Create Date: 2018-09-29 10:31:22.229381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6c8fdf401c'
down_revision = '67c34fc8c91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GaodeMapScene',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('city_adcode', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('longtitude', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('typecode', sa.String(length=20), nullable=True),
    sa.Column('classify', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('shape', sa.Text(), nullable=True),
    sa.Column('wgs_long', sa.Float(), nullable=True),
    sa.Column('wgs_lat', sa.Float(), nullable=True),
    sa.Column('wgs_shape', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GaodeMapScene')
    # ### end Alembic commands ###
